version: 2.1
# orbs:
#   node: circleci/node@3.0.0
workflows:
  lint:
    jobs:
      - lint

jobs:
  lint:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Deps
          command: npm install
      - run:
          name: Run Linter
          command: npm run lint
