export type SatelliteType = {
    nameOfSatellite: string,
    officialName: string,
    unRegistryCountry: string,
    operatorCountry: string,
    operator: string,
    users: string,
    purpose: string,
    detailedPurpose: string,
    classOfOrbit: string,
    typeOfOrbit: string,
    longitudeOfGeo: number,
    perigee: number,
    apogee: number,
    eccentricity: string,
    inclination: number,
    period: number,
    launchMass: number,
    dryMass: number,
    power: number,
    dateOfLaunch: string,
    expectedLifetime: number,
    contractor: string,
    countryOfContractor: string,
    launchSite: string,
    launchVehicle: string,
    cospar: number,
    norad: number
}

export type SatelliteKeys = keyof SatelliteType
